projeto/core/urls.py
from django.urls import path
from projeto.core import views as v

app_name ='core'

urlpatterns = [
    path('', v.index, name='index'),

]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v


app_name = 'produto'

urlpatterns = [
    path('', v.produto_list , name='produto_list'),
    path('<int:pk>/', v.produto_detail , name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),

]

projeto/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
]

projeto/core/models.py
from django.db import models

class TimeStempedModel(models.Model):

    created = models.DateTimeField(
        'criado em',
        auto_now_add = True,
        auto_now=False
        )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add = False,
        auto_now = True
        )

    class Meta:
        abstract = True

projeto/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from projeto.core.models import TimeStempedModel
from projeto.produto.models import Produto

MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)

class Estoque(TimeStempedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return {} - {} - {}.format(self.pk , self.nf, self.created.strftime('%d-%m-%Y'))

    def nf_formated(self):
        return str(self.nf).zfill(3)

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE)
    produto= models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{}-{}-{}'.format(self.pk, self.estoque.pk, self.produto)

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy

class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM' , max_length=8)
    produto = models.CharField('Produto' , max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque minimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk':self.pk})

projeto/produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

projeto/core/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

projeto/estoque/views.py
from django.shortcuts import render
from .models import Estoque

def estoque_entrada_list(request):
    template_name= 'estoque_entrada_list.html'
    objects = Estoque.objects.filter(movimento='e')
    context = {'object_list': objects}
    return render(request,template_name, context)

projeto/produto/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .models import Produto
from .forms import ProdutoForm


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def produto_add(request):
    template_name = 'produto_form.html'
    return render(request, template_name)

class ProdutoCreate(CreateView):
    model=Produto
    template_name='produto_form.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model=Produto
    template_name='produto_form.html'
    form_class = ProdutoForm

projeto/core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://djangoproject.com/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/d93c95203e.css">
    <style>
      body {
        margin-top:60px
      }
      .ok{
            color: green;
        }
      .no {
            color: red;
        }

    </style>
    {% block css%}{% endblock css%}
    <title>Estoque</title>
  </head>
  <body>
  {% include "includes/nav.html"%}
    <div class="container">
       {% block content%}{% endblock content%}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://use.fontwesome.com/a61b8cea1e"></script>


  {% block js %}{% endblock js%}
  </body>
</html>

projeto/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Estoque</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'core:index'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'produto:produto_list'%}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list'%}">Entrada</a>
                    <a class="dropdown-item" href="#">Saida</a>

                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pesquisar</button>
        </form>
    </div>
</nav>

projeto/core/templates/index.html
{% extends "base.html"%}

{% block content%}
<div class="jumbotron">
  <div class="container">
      <h1>Bem vindo</h1>
      <p>Este é um programa para controle de estoque</p>
      <p>
          <a href="https://github.com/moabjr/estoque">Veja no github</a>
      </p>


  </div>
</div>
{% endblock content%}

projeto/produto/templates/produto_detail.html
{% extends "base.html"%}

{% block content%}

    <a href="{%url 'produto:produto_list'%}">
        <button type="button" class="btn btn-primary">
            Voltar
        </button>
    </a>

<h1>{{object.produto}}
<span class="pull-right">
    <a href="{% url 'produto:produto_edit' object.pk %}">
        <button type="button" class="btn btn-success">
            <span class="fa fa-pencil"></span> Editar
        </button>
    </a>
</span>
</h1>
<div class="col-sm-6">
    <table class="table table-information">
        <tbody>
            <tr>
                <th class="text-right">Importado</th>
                <td>
                    {%if object.importado %}
                       <i class="fa fa-check-circle ok"></i>
                    {%else%}
                       <i class="fa fa-minus-circle no"></i>
                    {%endif%}
                </td>
            </tr>
            <tr>
                <th class="text-right">NCM</th>
                <td>{{object.ncm}}</td>
            </tr>
            <tr>
                <th class="text-right">Preço</th>
                <td>R$ {{object.preco}}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque</th>
                <td>{{object.estoque}}</td>
            </tr>

            <tr>
                <th class="text-right">Estoque minimo</th>
                <td>{{object.estoque_minimo}}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content%}

projeto/produto/templates/produto_form.html
{%extends 'base.html'%}

{%load widget_tweaks %}
{%block css%}
    <style>
        span.required:after {
            content: '*';
            color: red;
        }
    </style>

{%endblock css%}

{% block content%}

<form method="post" novalidate>
    {%csrf_token%}
    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %}has-error {% endif%}">
            <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                {% else %}
                    {{ field.label }}
                {% endif%}
            </label>
             {% render_field field class=" form-control "%}
             {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
             {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content%}

{% block js%}
<script>
    $('#id_importado').remoclass('form-control');
</script>
{% endblock js%}

projeto/produto/templates/produto_list.html
{% extends "base.html"%}
{% block css%}

{% endblock css%}
{% block content%}
<div class="page-header">

    <h2>
        Lista de Produtos
        <span class="pull-right">
            <a href="{% url 'produto:produto_add'%}">
                <button type="button" class="btn-btn-primary">
                    <span class="fa-fa-plus"></span> Adicionar
                </button>
            </a>
        </span>
    </h2>
    {% if object_list %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Importado</th>
                    <th>NCM</th>
                    <th>Produto</th>
                    <th>Preço</th>
                    <th class="text-center">Estoque</th>
                    <th class="text-center">Estoque Minimo</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list%}
                    <tr>
                        <td>
                            {%if object.importado %}
                                <i class="fa fa-check-circle ok"></i>
                            {%else%}
                                <i class="fa fa-minus-circle no"></i>
                            {%endif%}
                        </td>
                        <td>{{ object.ncm}}</td>
                        <td>
                            <a href="{{ object.get_absolute_url}}">{{ object.produto}}</a>
                        </td>
                        <td>R$ <span class="pull-right">{{ object.preco}}</span></td>
                        <td class="text-center">{{ object.estoque}}</td>
                        <td class="text-center">{{ object.estoque_minimo}}</td>
                    </tr>
                {% endfor%}
            </tbody>
        </table>
    {%else%}
        <p class="alert alert-warning">Sem itens na lista</p>
    {% endif  %}
</div>
{% endblock content%}